// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {goproxy} from '../models';

export function CheckClientActivity():Promise<void>;

export function ClientRequest(arg1:http.Request,arg2:goproxy.ProxyCtx):Promise<http.Request|http.Response>;

export function GetLastServerError():Promise<string>;

export function InitProxy():Promise<goproxy.ProxyHttpServer>;

export function OtherLog(arg1:number):Promise<void>;

export function SetMode(arg1:number,arg2:string):Promise<string>;

export function StartProxy(arg1:string):Promise<void>;

export function StopProxy():Promise<void>;
