// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckClientActivity() {
  return window['go']['main']['Proxy']['CheckClientActivity']();
}

export function ClientRequest(arg1, arg2) {
  return window['go']['main']['Proxy']['ClientRequest'](arg1, arg2);
}

export function GetLastServerError() {
  return window['go']['main']['Proxy']['GetLastServerError']();
}

export function InitProxy() {
  return window['go']['main']['Proxy']['InitProxy']();
}

export function OtherLog(arg1) {
  return window['go']['main']['Proxy']['OtherLog'](arg1);
}

export function SetMode(arg1, arg2) {
  return window['go']['main']['Proxy']['SetMode'](arg1, arg2);
}

export function StartProxy(arg1) {
  return window['go']['main']['Proxy']['StartProxy'](arg1);
}

export function StopProxy() {
  return window['go']['main']['Proxy']['StopProxy']();
}
