// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPort(arg1:number):Promise<boolean>;

export function CheckXML(arg1:string):Promise<string>;

export function Details(arg1:string):Promise<string>;

export function ExtractCUSA(arg1:string):Promise<string>;

export function ExtractVersion(arg1:string):Promise<string>;

export function ExtractXML(arg1:string):Promise<string>;

export function IsValidJSONURL(arg1:string):Promise<boolean>;

export function LocalIP():Promise<string>;

export function Mapper(arg1:string):Promise<string>;

export function OpenBrowser(arg1:string):Promise<void>;

export function PSNXML(arg1:string):Promise<string>;

export function TitleMetadataInfo(arg1:string):Promise<string>;
