// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPort(arg1) {
  return window['go']['main']['PSN']['CheckPort'](arg1);
}

export function CheckXML(arg1) {
  return window['go']['main']['PSN']['CheckXML'](arg1);
}

export function Details(arg1) {
  return window['go']['main']['PSN']['Details'](arg1);
}

export function ExtractCUSA(arg1) {
  return window['go']['main']['PSN']['ExtractCUSA'](arg1);
}

export function ExtractVersion(arg1) {
  return window['go']['main']['PSN']['ExtractVersion'](arg1);
}

export function ExtractXML(arg1) {
  return window['go']['main']['PSN']['ExtractXML'](arg1);
}

export function IsValidJSONURL(arg1) {
  return window['go']['main']['PSN']['IsValidJSONURL'](arg1);
}

export function LocalIP() {
  return window['go']['main']['PSN']['LocalIP']();
}

export function Mapper(arg1) {
  return window['go']['main']['PSN']['Mapper'](arg1);
}

export function OpenBrowser(arg1) {
  return window['go']['main']['PSN']['OpenBrowser'](arg1);
}

export function PSNXML(arg1) {
  return window['go']['main']['PSN']['PSNXML'](arg1);
}

export function TitleMetadataInfo(arg1) {
  return window['go']['main']['PSN']['TitleMetadataInfo'](arg1);
}
